# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build-and-tag:
    runs-on: windows-latest  
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19 

    - name: Build
      run: |
        go mod tidy
        go build -tags release

    - name: Create Tag
      run: |
        echo ::set-env name=TAG::v1.0.${{ github.run_number }}
        echo $TAG >> $GITHUB_ENV

    - name: Push Tag
      if: success()
      run: |
        git config --local user.email "754277710@qq.com"
        git config --local user.name "GitHub Action"
        git tag $TAG
        git push origin $TAG
